import type { Metadata } from "next";
import { siteConfig } from "@/config/site";

export const siteName = siteConfig.name;
export const siteTitle = siteConfig.title;
export const homeDescription =
  "Angular developer with 2+ years building a production project-management platform. Explore projects and experience — open to frontend and Angular roles.";

// The public base URL used for canonical, Open Graph, sitemap and robots URLs.
// Set NEXT_PUBLIC_SITE_URL to pin a domain. Otherwise Vercel's
// VERCEL_PROJECT_PRODUCTION_URL (the project's production domain, available at
// build time) is used, so a new domain assigned in Vercel is picked up on the
// next deploy without code changes.
function resolveSiteUrl() {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL;
  if (explicit) return explicit.replace(/\/+$/, "");

  const vercelProduction = process.env.VERCEL_PROJECT_PRODUCTION_URL;
  if (vercelProduction) return `https://${vercelProduction}`;

  return "http://localhost:3000";
}

export const siteUrl = resolveSiteUrl();

// Generated by app/opengraph-image.tsx.
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.title}. Angular, TypeScript, ASP.NET Core, PostgreSQL.`,
};

// Next.js merges metadata shallowly, so a page that sets `openGraph` or
// `twitter` replaces the layout's object entirely (including the file-based
// share image). This builds the full set for a page from its own title,
// description and path.
export function pageMetadata({
  title,
  description,
  path,
}: {
  title?: string;
  description: string;
  path: string;
}): Metadata {
  const fullTitle = title ? `${title} — ${siteName}` : siteTitle;

  return {
    ...(title && { title }),
    description,
    alternates: { canonical: path },
    openGraph: {
      title: fullTitle,
      description,
      url: path,
      siteName,
      type: "website",
      locale: "en_US",
      images: [shareImage],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [shareImage],
    },
  };
}
